# Generated by Django 4.2.16 on 2024-12-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nur', '0002_alter_customuser_address_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
