# Generated by Django 4.2.16 on 2024-12-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nur', '0007_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
