# Generated by Django 4.2.16 on 2024-12-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nur', '0010_client_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price of the product', max_digits=15),
        ),
    ]
