# Generated by Django 4.2.16 on 2024-12-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nur', '0011_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Product cost price', max_digits=15),
        ),
    ]
