# Generated by Django 4.2.16 on 2024-12-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nur', '0014_transaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
