# Generated by Django 4.2.16 on 2024-12-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nur', '0015_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
    ]
