# Generated by Django 4.2.16 on 2024-12-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nur', '0016_remove_customuser_city_remove_customuser_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
