# Generated by Django 4.2.16 on 2024-12-20 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nur', '0017_delete_city_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
